# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Ryansworks"
description: > # this means to ignore newlines until "email:"
   Developer and Musician blogging about VR, Webdev, Machine Learning, and Startups

email: ryan.mcdermott@ryansworks.com
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/background.jpg"

name: 'Ryan McDermott'
author: 'Ryan McDermott'
author_image: "/assets/images/ryan_mcdermott.jpg"

paginate:	5

url: "http://www.ryansworks.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ryansworks
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/ryanmcdermott
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
