# Permalinks
#
permalink:           pretty

# Setup
title:               Ryan McDermott
tagline:             'Software Developer'
description:         'Developer, musician, and lover of the great indoors'
url:                 http://ryanmcdermott.me
baseurl:             'http://ryanmcdermott.me'
paginate:            5

# About/contact
author:
  name:              Ryan McDermott
  url:               https://twitter.com/ryconolcast
  email:             ryansworks@gmail.com

# Custom vars
version:             1.0.0
