# Permalinks
#
permalink:           pretty

# Setup
title:               ryanswokrs
tagline:             'Ryan McDermott'
description:         'Developer, musician, and lover of the great indoors'
url:                 http://ryanmcdermott.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ryan McDermott
  url:               https://twitter.com/ryansworks
  email:             ryansworks@gmail.com

# Custom vars
version:             1.0.0
